# Generated by Django 5.1 on 2024-09-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(choices=[('Pe', 'Pereiro'), ('Pf', 'Pau dos Ferros'), ('Er', 'Ereré'), ('Sm', 'São Miguel')], default='', max_length=255),
        ),
    ]
